### ISSUE TITLE
Store SSL password in config

### ISSUE THREAD

**Issue by robcalcroft** [encharm/http-master#100]
Is there a way to locally store the PEM password for an SSL certificate? I am trying to make an upstart service for http-master however I can't enter the PEM password when I try and start the service. Can I specify the password in the command call? e.g. `http-master --config=~/config.conf --password=XXX`

**Comment by robcalcroft** [comment]
Ok fixed that by piping the password to the command, so this upstart file works now, can I open a pull request to merge it?

**Comment by Rush** [comment]
I just thought that setting password to the cert in command line is a really bad idea :) Why don't you decipher the password and have the file without it? Otherwise please open a pull request if you have some good solution but I think `--password` is not good cause it will show up on process list.

**Comment by robcalcroft** [comment]
Hmm, good point, could you expand on what you mean by "decipher the password and have the file without it"?

**Comment by Rush** [comment]
```
# you'll be prompted for your passphrase one last time
openssl rsa -in key.pem -out newkey.pem
```

**Comment by Rush** [comment]
Closing this unless there is still some reason to decipher the certs on the run
