### ISSUE TITLE
Feature request: optional CORS support

### ISSUE THREAD

**Issue by kumavis** [encharm/http-master#106]
it would be awesome if we could enable CORS support

**Comment by kumavis** [comment]
express has a nice drop in middleware
https://github.com/troygoode/node-cors

**Comment by Rush** [comment]
You could probably enable CORS right now with the header middleware. Not super nice but I think it does the job.

https://github.com/encharm/http-master#addheader

**Comment by kumavis** [comment]
ah yes that would work, thanks
