### ISSUE TITLE
Build error in apache-crypt

### ISSUE THREAD

**Issue by clcollins** [encharm/http-master#88]
Getting back to testing out the SNI stuff from #85 (been a busy few weeks at work), but I'm having some building problems.  Wondering if you can offer some guidance.

* Ubuntu 14.04 and 14.10 (fails on both)
* node 11.14 (as suggested in #85 ), built from nodejs.org tarball
* Build is running as root.  
* This is actually inside of a Docker image - I don't think that's relevant, but I thought I'd throw it out there.  Dockerfile here: [https://github.com/DockerDemos/http-master](https://github.com/DockerDemos/http-master)

If I run:

     npm install -g http-master

I receive:

     gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/0.11.14"

So I've used `--unsafe-perm` to work around that:

     npm install --unsafe-perm -g http-master

That gets farther but I get and error in the apache-crypt part of the build:

    make: Entering directory `/usr/local/lib/node_modules/http-master/node_modules/http-auth/node_modules/htpasswd/node_modules/apache-crypt/build'
      CXX(target) Release/obj.target/crypt3/deps/crypt3.o
    ../deps/crypt3.cc: In function 'const char* GetApacheSalt()':
    ../deps/crypt3.cc:18:20: error: 'time' was not declared in this scope
         srand(time(NULL));
                        ^
You can see the full error output in this gist, if you want it: [https://gist.github.com/clcollins/8356a62d104d5843a02d](https://gist.github.com/clcollins/8356a62d104d5843a02d) 

If this is not something guy folks can help with, no worries.  Any help you can provide is appreciated though.

**Comment by clcollins** [comment]
Trying this again today, and the issue appears to be resolved.  Got a clean build with the same environment and Dockerfile.  Thanks guys!

**Comment by Rush** [comment]
Glad to hear it works!
