### ISSUE TITLE
Is there a way to set maxSockets? I want to enable Keep Alive connections

### ISSUE THREAD

**Issue by szarouski** [encharm/http-master#95]
I would like to enable keep alive and I've seen following solution for http-proxy: https://github.com/nodejitsu/node-http-proxy/issues/767. I wonder if it is a similar solution for http-master and how could it be achieved?

Thank you

**Comment by Rush** [comment]
Yeah, you are welcome to try messing with https://github.com/encharm/http-master/blob/master/modules/middleware/proxy.js - you mean keep alive between proxy and target server, right?

**Comment by szarouski** [comment]
Correct. Thank you, I'll take a look.

**Comment by Rush** [comment]
@szarouski let me know your results. Perhaps it should be supported OOTB.

**Comment by szarouski** [comment]
Seems to be working fine if I do following:
add `var http = require('http');` at the top
And adjust proxy to include agent:
```js
var agent = new http.Agent({ maxSockets: Number.MAX_VALUE });
var proxy = httpProxy.createProxyServer({xfwd: true, agent: agent});
```

I wonder if that should be configurable? I don't know how options could be passed into middlewares.

I agree with you that it will be nice to have it OOTB. Let me know what should be next steps to make it happen :)

**Comment by Rush** [comment]
Just trying to think of disadvantages of this solution. I think the risk is that the server may more easily run out of available sockets. Have you done any benchmarking?

**Comment by szarouski** [comment]
Here is some feedback. I used http-proxy with agent created like above and I setup a load test using loadimpact.com with maximum at 250 connections. I was able to see that number of occupied sockets was growing over time. Once load test finished sockets state changed to [TIMED_WAIT](http://stackoverflow.com/questions/760819/is-there-a-limit-on-number-of-tcp-ip-connections-between-machines-on-linux). After 1 minute I could see that sockets on my linux machine were closed (indeed tcp_fin_timeout is 60). `ulimit` on my linux box was set to unlimited. From other comments I can see that TIMED_WAIT and number of available sockets [is depending](http://serverfault.com/questions/350643/exhausting-linux-machine-tcp-socket-limit-70k) on machine configuration. It seems that for default linux configuration there is a limit of [470 sockets at any given time](http://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux). So... I think that it would be nice to be able to configure agent settings. What do you think?

**Comment by szarouski** [comment]
Also something that I forgot to mention - it is not a `maxSockets` value which is making connection to change to 'keep-alive'. It is enough to just have http.Agent instance. I tried to debug core http module, but stuck on what exactly is causing it to pick keepAlive setting even when it is not set to true on the agent instance.

**Comment by szarouski** [comment]
Hi @Rush, I'll have some free time soon and I wonder if you can point me to what you think is the best way to define agent options and if there are any similar examples in the code where http-master takes configuration options. I'll make a PR once I'm done. Thank you sir.

**Comment by Rush** [comment]
Hey @szarouski, thanks for the offer. Actually I would rather appreciate some more tests to get a good default option. To answer your question, http-master uses dependency injection:

https://github.com/encharm/http-master/blob/master/modules/middleware/proxy.js#L32

Change it to:
```js
module.exports = function ProxyMiddleware(config, portConfig, di) {
```
and you have access to global config hash, where you could have `config.maxSockets`

Thanks!

**Comment by szarouski** [comment]
Proxy improvements, including agent settings landed here: https://github.com/encharm/http-master/pull/103. I'll try to contribute more when I have time. I'm not certain what editor you're using, but there is a great tool for realtime javascript development and testing called [wallaby.js](http://wallabyjs.com/), which is available for WebStorm, and soon for other editors. It was easy to get it working with your existing testing tools.

![http-master](https://cloud.githubusercontent.com/assets/911388/6510101/d7f166b8-c331-11e4-86d7-dfbd8949625d.gif)
<a href="https://cloud.githubusercontent.com/assets/911388/6510101/d7f166b8-c331-11e4-86d7-dfbd8949625d.gif" target="_blank">Open in new window</a>

**Comment by Nowaker** [comment]
@szarouski That's *huge*. Thanks for that. We'll both use it in our RubyMine.
