### ISSUE TITLE
Setting up http-master.service on Ubuntu 14

### ISSUE THREAD

**Issue by robcalcroft** [encharm/http-master#97]
Hi I'm having trouble setting up a service to control http-master. is there a way to implement e.g. `service start http-master` as systemd seems to have issues. 
Thanks

**Comment by Rush** [comment]
What kind of issues? Perhaps we could solve them. We use http-master internally as a systemd service.

**Comment by robcalcroft** [comment]
So my system doesn't have systemd or systemctl, I'm on Ubuntu 14.04, and when I move the .service file to the location specified I'm not able to use any of the suggested commands to start the service.

**Comment by Rush** [comment]
I see, you could contribute a service file specifically for Ubuntu 14.04 - for upstart. Unfortunately we are not going to make one ourselves since we don't use Ubuntu.

**Comment by robcalcroft** [comment]
Ah right ok. I may do that! :) 
Thanks for your help.
