### ISSUE TITLE
Proxying example.com/XXX to port

### ISSUE THREAD

**Issue by robcalcroft** [encharm/http-master#98]
Is it possible to proxy or redirect e.g. `example.com/HELLO` to `:PORT` or to serve static files. Wondering if this is possible. Thanks

**Comment by Rush** [comment]
Sure it is, just specify the following in your config:
```js
ports: {
  80: {
    router: {
      'example.com/hello/*': 8090
    }
  }
}
```

**Comment by robcalcroft** [comment]
So I just gave that a try and it looks like one of my other rules is taking precedence over it; my root has an API associated with it and I'm getting data from that not a proxy to Apache.
```
80: {
            "router": {
                   "domain.com/stuff/*": 9000,
                   "domain.com": "redirect -> https://domain.com/[path]",
                   "*": "redirect -> https://domain.com"
             },
},
```

**Comment by robcalcroft** [comment]
Is it possible to make the `'example.com/hello/*': 8090` be the root of my proxied app. As currently when I try it, it looks for `/hello/` in Apache whereas I'd like `example.com/hello/` to be the Apache root

**Comment by Rush** [comment]
That is something your end application needs to support anyway since all URLs  you generate have to account for the relative path. One could try actively re-write the HTML but in my opinion it is not worth the effort since you won't handle all the cases.

**Comment by robcalcroft** [comment]
Ok cool thanks :smile:
