### ISSUE TITLE
LogFileService: watcher is not defined

### ISSUE THREAD

**Issue by modiho** [encharm/http-master#99]
http-master crashes with

```
ReferenceError: watcher is not defined
    at FSWatcher.<anonymous> (/Users/Daniel/Projekte/Go-Lab/golab-git/server/la-server/node_modules/http-master/modules/services/logFile.js:34:15)
    at FSWatcher.emit (events.js:110:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1163:12)
```

[Relevant file/line](https://github.com/encharm/http-master/blob/master/modules/services/logFile.js#L34).

I am on OS X 10.10.2, using either node 0.12.0 or 0.10.29.

The error itself seems to be caused by a simple bug, but I wonder why an event with the `rename` action is triggered at all. When watching the files with `fs.watch` in another node process, no event with the `rename` action is triggered on the log files in the timeframe that the error occurs in.

Let me know if I can help you debug further. For me, commenting out the affected line in the source code works since I don't require any reloading functionality.

**Comment by Rush** [comment]
This is error is due to watching logFile being rotated .. you sure you're not moving log files?

**Comment by Rush** [comment]
Sorry, I actually checked the code now and it's indeed a stupid bug.
